services:
  - type: web
    name: auction-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 